# Generated by Django 3.1.1 on 2020-09-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=50, verbose_name='Ник')),
                ('job', models.CharField(max_length=200, verbose_name='Работа')),
                ('education', models.TextField(verbose_name='Место учебы')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
    ]
