# Generated by Django 2.2.12 on 2020-12-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='friends',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
